# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7fd73f859e134c8751ebbf2c278967657bff91a2eb2dc91161156280c12cf2fe8769ecc0ba8b30ae23864ef301f5d2952af26957e9e68186cafddf91a76bb01

test:
  secret_key_base: b971452c907d3b51cfb17e5a53b9f307f74b3d2795e89d5ff15e8d1df6f1324d8a4043e0922778fb85e371ccad7556d68ed5627f3b65782305f34e4b2f217007

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
